favicon: null
name: Vidas
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.75
  brandStrength: 0.7055541
  rhythmicContrast: 0.5
  brandColors:
    - '#eff4f7'
    - '#785b3d'
    - '#adb6b1'
    - '#341409'
    - '#fed09c'
  lightness: 0.25
typography_spectrum: 0.688172
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
