name: Vidas
favicon: null
layout_spectrum: 0.41528
typography_spectrum: 0.688172
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eff4f7'
    - '#785b3d'
    - '#adb6b1'
    - '#341409'
    - '#fed09c'
  brandStrength: 0.7055541
  lightness: 0.2148617
  saturation: 0.9850003
  rhythmicContrast: 0.9089096
purpose: []
